parameters:
  name: 'cistatus'
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 60
  cancelTimeoutInMinutes: 25
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      Python27:
        os_name:  ${{ parameters.name }}
        python_version: '2.7'
      Python37:
        os_name:  ${{ parameters.name }}
        python_version: '3.7'
    maxParallel: 2

  steps:
  - task: UsePythonVersion@0
    displayName: 'Python for test execution'
    inputs:
      versionSpec: $(python_version)
      addToPath: true
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip
      python -m pip install -r requirements-dev.txt
    displayName: 'Install requirements'

  - script: |
      flake8 --exit-zero --output flake8.xml --format=junit-xml
    displayName: 'Running Flake8 Static Analysis'
    continueOnError: true
    condition: eq(variables['os_name'], 'OSX')

  - task: PublishTestResults@2
    inputs:
      testRunner: JUnit
      testResultsFiles: flake8.xml
      testResultsTitle: Flake8 Results for $(os_name) with Python $(python_version)
      testRunTitle: Python-$(python_version)-$(os_name)-flake8
    condition: eq(variables['os_name'], 'OSX')

  - script: |
      pylint webdrivermanager/ test/ --exit-zero --output-format=junit > pylint.xml
    displayName: 'Running Pylint Static Analysis'
    continueOnError: true
    condition: and(eq(variables['os_name'], 'OSX'), ne(variables['python_version'],'2.7'))

  - task: PublishTestResults@2
    inputs:
      testRunner: JUnit
      testResultsFiles: pylint.xml
      testResultsTitle: PyLint Results for $(os_name) with Python $(python_version)
      testRunTitle: Python-$(python_version)-$(os_name)-pylint
      publishRunAttachments: true
    condition: and(eq(variables['os_name'], 'OSX'), ne(variables['python_version'],'2.7'))

  - script: python setup.py sdist
    displayName: 'Generate sdist files'
